name: Deploy to GitHub Pages

on:
  push:
    branches: [gh-pages]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.5"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --base-href /mithulram-portfolio/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
